---
nec_pkgs: libevent,libevent-devel,pcre,gcc,zlib,zlib-devel
servername: 
  - "{{ ansible_hostname }}"
thrd_amt: 
  - "{{ ansible_processor_vcpus }}"
mem_c: 
  - "{{ ( ansible_memtotal_mb - 1000 ) // 3 }}"
repo_epel: epel.repo
repo_epel_test: epel-testing.repo
