---
- name: transfer repo file
  copy:  src=mariadb.repo dest=/etc/yum.repo.d/
- name: install necessory packages
  yum: name="{{nec_pkgs}}" state=latest
- name: transfer client configuration conf_files
  template: src=client.cnf dest=/etc/my.cnf.d/
- name: transfer server configuration conf_files
  template: src=server.cnf dest=/etc/my.cnf.d/
- name: transfer mysql-clients configuration conf_files
  template: src=mysql-clients.cnf dest=/etc/my.cnf.d/
- name: start mariadb service
  service: name=mariadb state=started enabled=yes
  tags:
    - start mariadb
  notify:
    - modify mariadb user password
